apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgbadger-output-pvc
  namespace: hom
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: oci-fss # oke virtual node
