apiVersion: batch/v1
kind: CronJob
metadata:
  name: pgbadger-cron-hom
  namespace: hom
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: pgbadger
              image: iad.ocir.io/grsmpvipzqfz/pgbadger-cron-hom:latest
              imagePullPolicy: Always
              env:
                - name: OCI_CONFIG_FILE
                  value: /root/.oci/config
              volumeMounts:
                - name: oci-config
                  mountPath: /root/.oci
                  readOnly: true
                - name: output-volume
                  mountPath: /app/output
          restartPolicy: OnFailure
          volumes:
            - name: oci-config
              secret:
                secretName: oci-config-secret
            - name: output-volume
              persistentVolumeClaim:
                claimName: pgbadger-output-pvc
          imagePullSecrets:
            - name: ocirsecret
